# Generated by Django 4.0.1 on 2022-02-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgeon_api', '0002_remove_userscheckedin_has_checked_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscheckedin',
            name='check_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='country',
            field=models.CharField(blank=True, default='United States', max_length=50),
        ),
        migrations.DeleteModel(
            name='NotifyMe',
        ),
    ]
