# Generated by Django 4.0.1 on 2022-02-03 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgeon_api', '0003_alter_userscheckedin_check_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
