# Generated by Django 4.0.1 on 2022-02-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgeon_api', '0006_reviews_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_link', models.CharField(max_length=350)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
