# Generated by Django 4.0.1 on 2022-02-10 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgeon_api', '0007_stories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsUpdate',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
        migrations.DeleteModel(
            name='Stories',
        ),
    ]
