# Generated by Django 4.0.1 on 2022-02-13 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgeon_api', '0008_delete_newsupdate_delete_reviews_delete_stories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='slug',
        ),
        migrations.AddField(
            model_name='report',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(blank=True, default='', max_length=100)),
                ('notification_tag', models.CharField(blank=True, default='', max_length=100)),
                ('notification_title', models.CharField(blank=True, max_length=200)),
                ('notification_message', models.TextField(blank=True)),
                ('read', models.CharField(choices=[('Read', 'Read'), ('Not Read', 'Not Read')], default='Not Read', max_length=20)),
                ('notification_trigger', models.CharField(blank=True, choices=[('Triggered', 'Triggered'), ('Not Triggered', 'Not Triggered')], default='Triggered', max_length=100)),
                ('volunteer_id', models.CharField(blank=True, max_length=100)),
                ('partner_id', models.CharField(blank=True, max_length=100)),
                ('contact_id', models.CharField(blank=True, max_length=100)),
                ('report_id', models.CharField(blank=True, max_length=100)),
                ('client_id', models.CharField(blank=True, max_length=100)),
                ('posts_id', models.CharField(blank=True, max_length=100)),
                ('checked_in_id', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_receiving_notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
