# Generated by Django 4.0.1 on 2022-02-13 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgeon_api', '0009_remove_report_slug_report_views_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
