# Generated by Django 4.0.1 on 2022-02-24 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orgeon_api', '0011_remove_post_has_read_remove_post_need_replies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomments',
            name='time_created',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reportcomments',
            name='time_created',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
