# Generated by Django 4.0.1 on 2022-02-25 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orgeon_api', '0012_postcomments_time_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='has_read',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_doc',
        ),
        migrations.RemoveField(
            model_name='report',
            name='views',
        ),
        migrations.AddField(
            model_name='report',
            name='time_posted',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
