# Generated by Django 4.0.1 on 2022-02-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgeon_api', '0013_remove_report_has_read_remove_report_report_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_posted',
            field=models.DateField(auto_now_add=True),
        ),
    ]
