# Generated by Django 4.0.1 on 2022-02-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgeon_api', '0015_alter_report_time_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='time_posted',
        ),
        migrations.AlterField(
            model_name='report',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
